name: Deploy

on:
  push:
    branches:
      - icmods

concurrency: deploy

jobs:
  build:
    runs-on: ununtu-latest
    env:
      BRANCH_MASTER: icmods
      BRANCH_DEPLOY: deploy
      FRONTEND_DIRECTORY: apps/frontend
    if: github.event.workflow_run.conclusion != 'failure'
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ env.BRANCH_MASTER }}
        fetch-depth: 0
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Build
      run: pnpm run web:build
    - name: Configure git
      run: |
        git config --global user.name "MaXFeeD"
        git config --global user.email "maksfeed.mf@gmail.com"
        git config --global push.autoSetupRemote true
    - name: Run rm .git
      run: rm -frd .git
    - name: Push into deploy
      working-directory: ${{ env.FRONTEND_DIRECTORY }}/.output
      run: |
        git config --global init.defaultBranch $BRANCH_DEPLOY
        git init
        git add --force --all .
        git commit -m "Deploy" --quiet --no-verify
        git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git
        git push --force -u origin $BRANCH_DEPLOY
